routes/web.php
<?php

use App\Http\Controllers\Admin\ClientController;
use App\Http\Controllers\Admin\Courses\CourseRequestController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\LocationController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\Courses\CourseController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('front.index');
});

Route::prefix('admin')
    ->middleware('auth')
    ->name('admin.')->group(function(){
    Route::get('/', [HomeController::class, 'index']);
    Route::resource('users',UserController::class);
    Route::resource('clients',ClientController::class);
    Route::resource('courses',CourseController::class);
    Route::resource('locations',LocationController::class);
    Route::resource('course_requests',CourseRequestController::class);

    Route::get('course_requestss/selections',[CourseRequestController::class,'selections'])->name('course_requests.selections');
});

Auth::routes();

app/Models/CourseRequest.php
<?php

namespace App\Models;

use Eloquent;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Query\Builder;
use Illuminate\Http\Response;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

/**
 * App\Models\CourseRequest
 *
 * @property int $id
 * @property int $client_id
 * @property int $course_id
 * @property int $location_id
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property Carbon|null $deleted_at
 * @property-read Client $client
 * @property-read Course $course
 * @property-read Location $location
 * @method static \Illuminate\Database\Eloquent\Builder|CourseRequest newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|CourseRequest newQuery()
 * @method static Builder|CourseRequest onlyTrashed()
 * @method static \Illuminate\Database\Eloquent\Builder|CourseRequest query()
 * @method static \Illuminate\Database\Eloquent\Builder|CourseRequest whereClientId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|CourseRequest whereCourseId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|CourseRequest whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|CourseRequest whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|CourseRequest whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|CourseRequest whereLocationId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|CourseRequest whereUpdatedAt($value)
 * @method static Builder|CourseRequest withTrashed()
 * @method static Builder|CourseRequest withoutTrashed()
 * @mixin Eloquent
 */
class CourseRequest extends Model
{
    use HasFactory;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'client_id',
        'course_id',
        'location_id',
    ];

    /**
     * @return BelongsTo
     */
    public function course(): BelongsTo
    {
        return $this->belongsTo(Course::class);
    }

    /**
     * @return BelongsTo
     */
    public function client(): BelongsTo
    {
        return $this->belongsTo(Client::class);
    }

    /**
     * @return BelongsTo
     */
    public function location(): BelongsTo
    {
        return $this->belongsTo(Location::class);
    }

    public function makeNewRequest($request): Response
    {
        $client = Client::where('email', $request->email)->first();
        $course = CourseRequest::where(['course_id' => $request->course_id, 'client_id' => $client->id, 'location_id' => $request->location_id])->first();

        if($course){
            return response(['status'=>'failed','message'=>'course request already registered']);
        }

        DB::transaction(function () use ($request, $client) {
            if (!$client) {
                $client = Client::create([
                    'first_name' => $request->first_name,
                    'last_name' => $request->last_name,
                    'phone' => $request->phone,
                    'email' => $request->email,
                    'address' => $request->address,
                ]);
            }

            $this->fill([
                'course_id' => $request->course_id,
                'client_id' => $client->id,
                'location_id' => $request->location_id,
            ])->save();

        });

        return response(['status'=>'ok','message'=>'course ' . $this->course->title . ' request registered successfully']);
    }
}

app/Http/Controllers/Admin/Courses/CourseRequestController.php
<?php

namespace App\Http\Controllers\Admin\Courses;

use App\Http\Controllers\Controller;
use App\Http\Requests\UpdateCourseRequestsRequest;
use App\Models\Client;
use App\Models\Course;
use App\Models\CourseRequest;
use App\Models\Location;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;


class CourseRequestController extends Controller
{
    /**
     * @return View
     */
    public function index(): view
    {
        $course_requests = CourseRequest::with(['course', 'client', 'location'])->get();
        return view('admin.course_requests.index', compact('course_requests'));
    }

    /**
     * @return View
     */
    public function create(): view
    {
        return $this->edit(new CourseRequest());
    }

    /**
     * @param UpdateCourseRequestsRequest $request
     * @return RedirectResponse
     */
    public function store(UpdateCourseRequestsRequest $request): RedirectResponse
    {
        return $this->update($request, new CourseRequest());
    }

    /**
     * @param CourseRequest $courseRequest
     * @return View
     */
    public function edit(CourseRequest $courseRequest): view
    {
        $model = $courseRequest;
        $clients = Client::get();
        $courses = Course::get();
        $locations = Location::get();

        return view('admin.course_requests.edit', compact('model', 'clients', 'courses', 'locations'));
    }

    /**
     * @param UpdateCourseRequestsRequest $request
     * @param CourseRequest $courseRequest
     * @return RedirectResponse
     */
    public function update(UpdateCourseRequestsRequest $request, CourseRequest $courseRequest): RedirectResponse
    {
        $courseRequest->fill($request->all())->save();
        return redirect()->route('admin.course_requests.index');
    }

    /**
     * @param Request $request
     * @return Response
     */
    public function selections(Request $request): Response
    {
        $courseId = $request->modelId;
        $term = $request->searchTerm;

        $locations = Location::with('courses')->whereHas('courses', function ($query) use ($courseId) {
            $query->where('courses.id', $courseId);
        })->where(function ($query) use ($term) {
            return $term ? $query->where('title', 'like', $term . '%') : $query;
        })->get();

        $results = [];
        foreach ($locations as $location) {
            $results[] = [
                'id' => $location->id,
                'text' => $location->title
            ];
        }

        return response($results);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/course_requests/edit.blade.php
@extends('admin.layouts.page',['content_title'=>trans('app.course_requests')])

@section('content')
    <?php
    if ($model->exists) {
        $tableColor = 'primary';
        $action = 'edit';
        $route = route('admin.course_requests.update', $model);
    } else {
        $tableColor = 'success';
        $action = 'create';
        $route = route('admin.course_requests.store');
    }
    ?>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">

                    <div class="card card-{{$tableColor}}">
                        <div class="card-header">
                            <h3 class="card-title">@lang('app.new_entry')</h3>
                        </div>

                        <form action="{{$route}}" method="POST">
                            @if($model->exists)
                                @method('PUT')
                            @endif
                            @csrf()
                            <div class="card-body row">
                                <div class="form-group col-4">
                                    <label for="course">@lang('app.client')</label>
                                    <select class="select2" name="client_id" id="client"
                                            data-placeholder="select client" style="width: 100%;">
                                        @foreach($clients as $client)
                                            <option
                                                {{$model->client_id === $client ? 'selected=selected' : ''}} value="{{$client->id}}">
                                                {{$client->first_name}} {{$client->last_name}}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group col-4">
                                    <label for="course">@lang('app.course')</label>
                                    <select class="select2" name="course_id" id="course"
                                            data-placeholder="select course" style="width: 100%;">
                                        @foreach($courses as $course)
                                            <option
                                                {{$model->course_id === $course ? 'selected=selected' : ''}} value="{{$course->id}}">
                                                {{$course->title}}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group col-4">
                                    <label for="course">@lang('app.location')</label>
                                    <select class="select2" name="location_id" id="location" data-placeholder="select location" style="width: 100%;"></select>
                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">@lang('app.submit')</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@section('js')
    @parent
    <script>
        let route = "{{route('admin.course_requests.selections')}}",
            parent = $('#course'),
            target = $('#location');
        parent.on('change.select2', function () {
            let modelId = $(this).val();
            target.select2().val(null)
            App.getSelections(route, target, modelId);
        });
        parent.trigger('change');
    </script>
@endsection

resources/views/admin/course_requests/index.blade.php
@extends('admin.layouts.page',['content_title'=>trans('app.course_requests')])

@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">@lang('app.list')</h3>
                            <div>
                                <a href="{{route('admin.course_requests.create')}}" style = "float:right" class="btn btn-success" href="">@lang('app.new')</a>
                            </div>
                        </div>
                        <div class="card-body">
                            <div id="course_table_wrapper" class="dataTables_wrapper dt-bootstrap4">
                                <div class="row">
                                    <div class="col-sm-12 col-md-6"></div>
                                    <div class="col-sm-12 col-md-6"></div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <table id="course_table"
                                               class="table table-bordered table-hover dataTable dtr-inline"
                                               role="grid" aria-describedby="example2_info">
                                            <thead>
                                            <tr role="row">
                                                <th class="sorting sorting_asc" tabindex="0" rowspan="1" colspan="1"
                                                    aria-sort="ascending">
                                                    @lang('app.created_at')
                                                </th>
                                                <th class="sorting" tabindex="0" rowspan="1" colspan="1">
                                                    @lang('app.client')
                                                </th>
                                                <th class="sorting" tabindex="0" rowspan="1" colspan="1">
                                                    @lang('app.course')
                                                </th>
                                                <th class="sorting" tabindex="0" rowspan="1" colspan="1">
                                                    @lang('app.location')
                                                </th>
                                                <th class="sorting" tabindex="0" rowspan="1" colspan="1">
                                                    @lang('app.actions')
                                                </th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            @foreach($course_requests as $course_request)
                                                <tr class="odd">
                                                    <td>{{$course_request->created_at ?? ''}}</td>
                                                    <td>
                                                        {{$course_request->client ?
                                                          $course_request->client->first_name . ' ' .
                                                          $course_request->client->last_name: ''}}
                                                    </td>
                                                    <td>{{$course_request->course ?  $course_request->course->title : ''}}</td>
                                                    <td>{{$course_request->location ?  $course_request->location->title : ''}}</td>
                                                    <td><a class="btn btn-info"
                                                           href="{{route('admin.course_requests.edit', $course_request->id)}}">@lang('app.edit')</a>
                                                    </td>
                                                </tr>
                                            @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection