routes/web.php
<?php

use App\Http\Controllers\Admin\ClientController;
use App\Http\Controllers\Admin\Courses\CourseRequestController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\LocationController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\Courses\CourseController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('front.index');
});

Route::prefix('admin')
    ->middleware('auth')
    ->name('admin.')->group(function(){
    Route::get('/', [HomeController::class, 'index']);
    Route::resource('users',UserController::class);
    Route::resource('clients',ClientController::class);
    Route::resource('courses',CourseController::class);
    Route::resource('locations',LocationController::class);
    Route::resource('course_requests',CourseRequestController::class);

    Route::get('course_requestss/selections',[CourseRequestController::class,'selections'])->name('course_requests.selections');
});

Auth::routes();

app/Models/User.php
<?php

namespace App\Models;

use App\Http\Services\ImageMaker;
use Database\Factories\UserFactory;
use Eloquent;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Query\Builder;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\DatabaseNotification;
use Illuminate\Notifications\DatabaseNotificationCollection;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Carbon;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Throwable;

/**
 * App\Models\User
 *
 * @property int $id
 * @property string $first_name
 * @property string $last_name
 * @property string $email
 * @property string $phone
 * @property string $address
 * @property Carbon|null $email_verified_at
 * @property string $password
 * @property string|null $remember_token
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property Carbon|null $deleted_at
 * @property-read DatabaseNotificationCollection|DatabaseNotification[] $notifications
 * @property-read int|null $notifications_count
 * @method static UserFactory factory(...$parameters)
 * @method static \Illuminate\Database\Eloquent\Builder|User newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|User newQuery()
 * @method static Builder|User onlyTrashed()
 * @method static \Illuminate\Database\Eloquent\Builder|User query()
 * @method static \Illuminate\Database\Eloquent\Builder|User whereAddress($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereEmailVerifiedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereFirstName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereLastName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User wherePassword($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User wherePhone($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereRememberToken($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereUpdatedAt($value)
 * @method static Builder|User withTrashed()
 * @method static Builder|User withoutTrashed()
 * @mixin Eloquent
 */
class User extends Authenticatable
{
    use HasFactory, Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'phone',
        'address',
        'image',
        'password',
    ];

    /**
     * Hash password
     * @param $input
     */
    public function setPasswordAttribute($input)
    {
        if ($input)
            $this->attributes['password'] = app('hash')->needsRehash($input) ? Hash::make($input) : $input;
    }

    /**
     * @return string
     */
    public function getFullNameAttribute(): string
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * @return BelongsToMany
     */
    public function images(): BelongsToMany
    {
        return $this->belongsToMany(Image::class);
    }

    /**
     * @param $request
     * @throws Throwable
     */
    public function createUser($request)
    {
        DB::transaction(function () use ($request) {
            //create user
            $this->fill($request->all())->save();
            //get image ids
            $imageIds = Image::handleImageInsert($request);
            //sync images
            $this->images()->sync($imageIds);
        });
    }

}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use App\Http\Requests\UpdateUsersRequest;
use Throwable;

class UserController extends Controller
{
    /**
     * @return View
     */
    public function index(): View
    {
        $users = User::with('images')->get();
        return view('admin.users.index', compact('users'));
    }

    /**
     * @return View
     */
    public function create(): View
    {
        return $this->edit(new User());
    }

    /**
     * @param UpdateUsersRequest $request
     * @return RedirectResponse
     */
    public function store(UpdateUsersRequest $request): RedirectResponse
    {
        return $this->update($request, new User());
    }

    /**
     * @param User $user
     * @return View
     */
    public function edit(User $user): View
    {
        $model = $user;
        return view('admin.users.edit', compact('model'));
    }

    /**
     * @param UpdateUsersRequest $request
     * @param User $user
     * @return RedirectResponse
     * @throws Throwable
     */
    public function update(UpdateUsersRequest $request, User $user): RedirectResponse
    {
        $user->createUser($request);
        return redirect()->route('admin.users.index');
    }
}

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.page',['content_title'=>trans('app.users')])

@section('content')
    <?php
    if ($model->exists) {
        $tableColor = 'primary';
        $action = 'edit';
        $route = route('admin.users.update', $model);
    } else {
        $tableColor = 'success';
        $action = 'create';
        $route = route('admin.users.store');
    }
    ?>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">

                    <div class="card card-{{$tableColor}}">
                        <div class="card-header">
                            <h3 class="card-title">@lang('app.new_entry')</h3>
                        </div>

                        <form action="{{$route}}" method="POST" enctype="multipart/form-data">

                            @if($model->exists)
                                @method('PUT')
                            @endif
                            @csrf()
                            <div class="card-body row">
                                <div class="form-group col-4">
                                    <label for="first_name">@lang('app.first_name')</label>
                                    <input type="text" class="form-control" name="first_name" id="first_name"
                                           value="{{$model->first_name ?? ''}}"
                                           placeholder="@lang('app.enter_first_name')">
                                </div>

                                <div class="form-group col-4">
                                    <label for="last_name">@lang('app.last_name')</label>
                                    <input type="text" class="form-control" name="last_name" id="last_name"
                                           value="{{$model->last_name ?? ''}}"
                                           placeholder="@lang('app.enter_last_name')">
                                </div>

                                <div class="form-group col-4">
                                    <label for="email">@lang('app.email')</label>
                                    <input type="email" class="form-control" name="email" id="email"
                                           value="{{$model->email ?? ''}}" placeholder="@lang('app.enter_email')">
                                </div>

                                <div class="form-group col-4">
                                    <label for="phone">@lang('app.phone')</label>
                                    <input type="text" class="form-control" name="phone" id="phone"
                                           value="{{$model->phone ?? ''}}" placeholder="@lang('app.enter_phone')">
                                </div>

                                <div class="form-group col-4">
                                    <label for="address">@lang('app.address')</label>
                                    <input type="text" class="form-control" name="address" id="address"
                                           value="{{$model->address ?? ''}}" placeholder="@lang('app.enter_address')">
                                </div>

                                <div class="form-group col-4">
                                    <label for="password">@lang('app.password')</label>
                                    <input {{$model->exists ? 'disabled' : ''}} type="password" class="form-control"
                                           name="password" id="password"
                                           value="{{$model->password ?? ''}}" placeholder="@lang('app.enter_password')">
                                </div>
                                <div class="form-group col-4">
                                    <div class="image_container">
                                        @foreach($model->images as $image)
                                            <div class="image_block">
                                                <span class="remove_image"><i class="fas fa-window-close"></i></span>
                                                 <a href="/storage/uploads/images/original/{{$image->title ?? ''}}">
                                                    <img src="/storage/uploads/images/thumb/{{$image->title ?? ''}}" alt="not available" width="80"/>
                                                </a>
                                                 <input type="hidden" name="old_images[]" class="images_input" value="{{$image->title}}">
                                            </div>
                                        @endforeach
                                    </div>
                                    <input multiple type="file" name="images[]" class="images_input" id="user_images">
                                    <label class="images" for="images">@lang('app.select_image')</label>
                                    <div id="image_display">

                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">@lang('app.submit')</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
@section('js')
    <script>
        $('.remove_image').click(function(){
            $(this).closest('.image_block').remove();
        });
    </script>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.page',['content_title'=>trans('app.users')])

@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">@lang('app.list')</h3>
                            <div>
                                <a href="{{route('admin.users.create')}}" style = "float:right" class="btn btn-success" href="">@lang('app.new')</a>
                            </div>
                        </div>
                        <div class="card-body">
                            <div id="user_table_wrapper" class="dataTables_wrapper dt-bootstrap4">
                                <div class="row">
                                    <div class="col-sm-12 col-md-6"></div>
                                    <div class="col-sm-12 col-md-6"></div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <table id="user_table"
                                               class="table table-bordered table-hover dataTable dtr-inline"
                                               role="grid" aria-describedby="example2_info">
                                            <thead>
                                            <tr role="row">
                                                <th class="sorting sorting_asc" tabindex="0" rowspan="1" colspan="1"
                                                    aria-sort="ascending">
                                                    @lang('app.created_at')
                                                </th>
                                                <th class="sorting" tabindex="0" rowspan="1" colspan="1">
                                                    @lang('app.first_name')
                                                </th>
                                                <th class="sorting" tabindex="0" rowspan="1" colspan="1">
                                                    @lang('app.last_name')
                                                </th>
                                                <th class="sorting" tabindex="0" rowspan="1" colspan="1">
                                                    @lang('app.phone')
                                                </th>
                                                <th class="sorting" tabindex="0" rowspan="1" colspan="1">
                                                    @lang('app.address')
                                                </th>
                                                <th class="sorting" tabindex="0" rowspan="1" colspan="1">
                                                    @lang('app.image')
                                                </th>
                                                <th class="sorting" tabindex="0" rowspan="1" colspan="1">
                                                    @lang('app.actions')
                                                </th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            @foreach($users as $user)
                                                <tr class="odd">
                                                    <td>{{$user->created_at ?? ''}}</td>
                                                    <td>{{$user->first_name ?? ''}}</td>
                                                    <td>{{$user->last_name ?? ''}}</td>
                                                    <td>{{$user->phone ?? ''}}</td>
                                                    <td>{{$user->address ?? ''}}</td>
                                                    <td>
                                                        @foreach($user->images as $image)
                                                            <a href="/storage/uploads/images/original/{{$image->title ?? ''}}" class="table_image_link">
                                                                <img src="/storage/uploads/images/thumb/{{$image->title ?? ''}}" alt="not available" width="80"/>
                                                            </a>
                                                        @endforeach
                                                    </td>
                                                    <td><a class="btn btn-info"
                                                           href="{{route('admin.users.edit', $user->id)}}">@lang('app.edit')</a>
                                                    </td>
                                                </tr>
                                            @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection